Repository networkupstools/nut, pull requests merged in 2021-05, with the labels that each got.

#974 Add USB device number matching
  docs/man/blazer-common.txt
  docs/man/nutdrv_qx.txt
  docs/man/tripplite_usb.txt
  docs/man/usbhid-ups.txt
  drivers/blazer_usb.c
  drivers/libusb.c
  drivers/nutdrv_qx.c
  drivers/riello_usb.c
  drivers/tripplite_usb.c
  drivers/usb-common.c
  drivers/usb-common.h
  drivers/usbhid-ups.c
Labels: USB, enhancement, ready / code review, ready / gonna merge

#1034 Add mock for TcpClient (C++)
  clients/Makefile.am
  clients/nutclient.h
  clients/nutclientmem.cpp
  clients/nutclientmem.h
  configure.ac
  drivers/bcmxcp_ser.c
  lib/.gitignore
  lib/Makefile.am
  lib/libnutclientstub.pc.in
  tests/Makefile.am
  tests/nutclienttest.cpp
Labels: C++

#538 Support CyberPower OR1500LCDRTXL2U with powerpanel driver
  drivers/powerp-bin.c
  drivers/powerp-txt.c
  drivers/powerpanel.h
Labels: ready / gonna merge
