Repository networkupstools/nut, pull requests merged in 2021-03, with the labels that each got.

#733 Changes to add support for AMETEK Powervar UPM as usb-hid UPS.
  docs/acknowledgements.txt
  docs/man/usbhid-ups.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/libusb.c
  drivers/powervar-hid.c
  drivers/powervar-hid.h
  drivers/usbhid-ups.c
Labels: ready / gonna merge

#991 docs/developers.txt: replace "master" where it is easy…
  docs/developers.txt
Labels: documentation

#989 Docs update and clarification
  clients/upsmon.c
  conf/upsmon.conf.sample.in
  docs/config-notes.txt
  docs/man/upsmon.txt
  docs/net-protocol.txt
  docs/security.txt
Labels: documentation

#990 Easy fixes for issue #840
  docs/security.txt
  docs/solaris-usb.txt
  drivers/asem.c
  drivers/nutdrv_qx.c
  drivers/phoenixcontact_modbus.c
  drivers/usbhid-ups.c
Labels: documentation

#992 Retire some terminology
  NEWS
  README
  clients/nutclient.cpp
  clients/nutclient.h
  clients/upsmon.c
  clients/upsmon.h
  conf/ups.conf.sample
  conf/upsd.users.sample
  conf/upsmon.conf.sample.in
  docs/config-notes.txt
  docs/design.txt
  docs/features.txt
  docs/history.txt
  docs/man/clone.txt
  docs/man/genericups.txt
  docs/man/libnutclient_misc.txt
  docs/man/nut.conf.txt
  docs/man/nutdrv_atcl_usb.txt
  docs/man/richcomm_usb.txt
  docs/man/upsd.txt
  docs/man/upsd.users.txt
  docs/man/upsmon.conf.txt
  docs/man/upsmon.txt
  docs/net-protocol.txt
  docs/new-drivers.txt
  docs/nut.dict
  docs/scheduling.txt
  docs/security.txt
  drivers/optiups.c
  scripts/augeas/README
  scripts/augeas/nutupsdusers.aug.in
  scripts/augeas/tests/test_nut.aug
  scripts/perl/Nut.pm
  scripts/python/app/README
  scripts/python/module/PyNUT.py
  server/netcmds.h
  server/netuser.c
  server/netuser.h
  server/user.c
Labels: WIP, documentation, enhancement
