Repository networkupstools/nut, pull requests merged in 2021-09, with the labels that each got.

#1052 generic modbus driver
  configure.ac
  docs/Makefile.am
  docs/man/Makefile.am
  docs/man/generic_modbus.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/generic_modbus.c
  drivers/generic_modbus.h
Labels: ready / gonna merge

#1054 systemd/*.service(.in): update units with SyslogIdentifier=%N
  scripts/systemd/nut-driver-enumerator.service.in
  scripts/systemd/nut-driver@.service.in
  scripts/systemd/nut-monitor.service.in
  scripts/systemd/nut-server.service.in
Labels: ready / gonna merge

#1099 Use ci_build.sh for CI spellchecks, and check some more docs files
  Jenkinsfile-dynamatrix
  ci_build.sh
  docs/Makefile.am
  docs/nut.dict
Labels: CI, ready / gonna merge

#1043 server: Add option to disable weak SSL protocols/ciphers.
  conf/upsd.conf.sample
  docs/nut.dict
  server/conf.c
  server/netssl.c
  server/netssl.h
Labels: need testing, ready / code review, ready / gonna merge
