Repository networkupstools/nut, pull requests merged in 2021-11, with the labels that each got.

#954 Modbus driver for Huawei UPS2000/2000A (1kVA-3kVA)
  docs/man/Makefile.am
  docs/man/huawei-ups2000.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/huawei-ups2000.c
Labels: ready / gonna merge

#276 SNMP: Power on and power off delay time writing; timeticks support;
  drivers/apc-mib.c
  drivers/snmp-ups.c
  drivers/snmp-ups.h
Labels: bug, ack, need testing, ready / gonna merge

#1044 HID-compliant UPS support with interface gt than 0 + Arduino UPS support
  drivers/Makefile.am
  drivers/arduino-hid.c
  drivers/arduino-hid.h
  drivers/libusb.c
  drivers/libusb.h
  drivers/powervar-hid.c
  drivers/usbhid-ups.c
  scripts/upower/95-upower-hid.rules
Labels: need testing, ready / code review, USB, ready / gonna merge

#1162 Fix sanity-checking of the ability to run CppUnit tests
  clients/Makefile.am
  clients/nutclient.cpp
  clients/nutclient.h
  configure.ac
  drivers/Makefile.am
  server/Makefile.am
  tests/Makefile.am
  tests/nutclienttest.cpp
  tools/nut-scanner/Makefile.am
Labels: CI

#1171 CI/LXC setup doc refresh
  docs/ci-farm-lxc-setup.txt
  docs/config-prereqs.txt
  docs/nut.dict
Labels: documentation, CI

#1170 CI: Revise builds with older autoconf and related tool kits
  .gitignore
  Makefile.am
  ci_build.sh
  clients/Makefile.am
  common/Makefile.am
  conf/Makefile.am
  configure.ac
  data/Makefile.am
  data/html/Makefile.am
  docs/Makefile.am
  docs/cables/Makefile.am
  docs/man/Makefile.am
  drivers/Makefile.am
  include/Makefile.am
  lib/Makefile.am
  scripts/Makefile.am
  scripts/Solaris/Makefile.am
  scripts/augeas/Makefile.am
  scripts/devd/Makefile.am
  scripts/hotplug/Makefile.am
  scripts/python/Makefile.am
  scripts/systemd/Makefile.am
  scripts/udev/Makefile.am
  scripts/ufw/Makefile.am
  scripts/upsdrvsvcctl/Makefile.am
  server/Makefile.am
  tests/Makefile.am
  tools/Makefile.am
  tools/nut-scanner/Makefile.am
Labels: CI

#1183 Fightwarn: short global variable names and other minor alerts from LGTM.com
  ci_build.sh
  drivers/bcmxcp_ser.c
  drivers/bcmxcp_ser.h
  drivers/bcmxcp_usb.c
  drivers/bestfortress.c
  drivers/phoenixcontact_modbus.c
  tools/nut-scanner/scan_eaton_serial.c
Labels: refactor/fightwarn

#1185 fightwarn: drivers/nutdrv_qx_masterguard.c: printf() assumes…
  drivers/nutdrv_qx_masterguard.c
Labels: refactor/fightwarn

#1194 More fixes for builds on older platforms
  autogen.sh
  ci_build.sh
  configure.ac
  docs/config-prereqs.txt
  docs/nut.dict
  scripts/augeas/.gitignore
  scripts/devd/Makefile.am
  scripts/udev/.gitignore
  scripts/udev/Makefile.am
Labels: documentation, CI, refactor/fightwarn

#1195 drivers/snmp-ups.{c,h}: typedef snmp_info_t::flags and …
  drivers/snmp-ups.c
  drivers/snmp-ups.h
Labels: SNMP, refactor/fightwarn

#1196 docs/FAQ.txt: update for use-cases of dummy-ups in relay mode
  docs/FAQ.txt
Labels: documentation

#1197 docs/FAQ.txt: update for interactions via github (issues, PRs, ...)
  docs/FAQ.txt
Labels: documentation

#1199 Initial release for Salicru driver
  data/driver.list.in
  drivers/Makefile.am
  drivers/salicru-hid.c
  drivers/salicru-hid.h
  drivers/usbhid-ups.c
  scripts/upower/95-upower-hid.rules
Labels: USB, ready / gonna merge

#1203 More fixes for builds on older platforms (OpenBSD 6.4)
  common/Makefile.am
  configure.ac
  docs/config-prereqs.txt
  docs/nut.dict
Labels: documentation, CI, refactor/fightwarn

#1200 docs/FAQ.txt: extend Q&A on "NUT proxying" with mention of "clone" driver
  docs/FAQ.txt
Labels: documentation

#1198 Huawei UPS2000: Update Man Page, Change Logic for "load.on" command
  docs/man/huawei-ups2000.txt
  docs/nut.dict
  drivers/huawei-ups2000.c
Labels: ready / gonna merge, modbus

#1204 Replace strcmp() and strcasecmp() use-cases for short fixed string args…
  clients/upsclient.c
  clients/upslog.c
  clients/upsmon.c
  clients/upsrw.c
  clients/upssched.c
  clients/upsset.c
  common/state.c
  common/upsconf.c
  docs/developers.txt
  docs/nut.dict
  drivers/apcsmart-old.c
  drivers/apcsmart.c
  drivers/apcupsd-ups.c
  drivers/belkin.c
  drivers/belkinunv.c
  drivers/bestups.c
  drivers/clone-outlet.c
  drivers/clone.c
  drivers/dstate.c
  drivers/gamatronic.c
  drivers/huawei-ups2000.c
  drivers/main.c
  drivers/masterguard.c
  drivers/mge-utalk.c
  drivers/mge-xml.c
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx_bestups.c
  drivers/nutdrv_qx_blazer-common.c
  drivers/nutdrv_qx_voltronic-qs-hex.c
  drivers/nutdrv_qx_voltronic-qs.c
  drivers/nutdrv_qx_voltronic.c
  drivers/oneac.c
  drivers/powercom.c
  drivers/powerman-pdu.c
  drivers/powerp-txt.c
  drivers/snmp-ups.c
  drivers/tripplite_usb.c
  drivers/upscode2.c
  drivers/victronups.c
  server/conf.c
  server/netget.c
  server/netlist.c
  server/netset.c
  server/user.c
  tests/cpputest.cpp
  tools/nut-scanner/nut-scanner.c
  tools/nut-scanner/scan_snmp.c
Labels: documentation, refactor/fightwarn

#1205 configure.ac: AC_LANG_PUSH before AC_COMPILE_IFELSE and similar tests
  Jenkinsfile-dynamatrix
  configure.ac
  m4/ax_c___attribute__.m4
  m4/nut_check_headers_windows.m4
  m4/nut_check_libnetsnmp.m4
  m4/nut_func_getnameinfo_argtypes.m4
  m4/nut_type_socklen_t.m4
Labels: bug, CI, refactor/fightwarn

#1207 CI/BUILD: avoid directly calling *-config progs from m4 functions
  docs/configure.txt
  m4/nut_check_libgd.m4
  m4/nut_check_libnetsnmp.m4
  m4/nut_check_libpowerman.m4
  m4/nut_check_libusb.m4
  m4/nut_check_libwrap.m4
  m4/nut_check_pkgconfig.m4
Labels: CI, refactor/fightwarn
