Repository networkupstools/nut, pull requests merged in 2021-04, with the labels that each got.

#638 Add support for Hunnox HNX-850
  docs/man/nutdrv_qx.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx_hunnox.c
  drivers/nutdrv_qx_hunnox.h
Labels: USB

#1008 nutdrv_qx: add support for SNR-UPS-LID-XXXX
  data/driver.list.in
  docs/acknowledgements.txt
  docs/man/nutdrv_qx.txt
  docs/nut.dict
  drivers/nutdrv_qx.c
Labels: HCL, USB, need testing, ready / code review, ready / gonna merge

#987 Add support for Delta UPS Amplon R Series
  data/driver.list.in
  drivers/Makefile.am
  drivers/delta_ups-hid.c
  drivers/delta_ups-hid.h
  drivers/usbhid-ups.c
Labels: feature, ready / code review

#963 Add Tripplite AVR750U (0x3024). Use smart1500lcdt_scale
  drivers/tripplite-hid.c
  scripts/upower/95-upower-hid.rules
Labels: Tripp Lite
