Repository networkupstools/nut, pull requests merged in 2021-12, with the labels that each got.

#1213 Trace snmp-ups MIB-probing better
  drivers/snmp-ups.c
Labels: enhancement, SNMP

#1215 Fightwarn: more alignment of ints sizes and signedness
  drivers/apcsmart-old.c
  drivers/apcsmart-old.h
  drivers/apcsmart.c
  drivers/apcsmart.h
  drivers/arduino-hid.c
  drivers/blazer.c
  drivers/blazer.h
  drivers/blazer_ser.c
  drivers/blazer_usb.c
  drivers/clone-outlet.c
  drivers/clone.c
  drivers/microsol-common.c
  drivers/netxml-ups.c
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx.h
  drivers/nutdrv_qx_bestups.c
  drivers/nutdrv_qx_blazer-common.c
  drivers/nutdrv_qx_masterguard.c
  drivers/nutdrv_qx_mecer.c
  drivers/nutdrv_qx_voltronic-qs-hex.c
  drivers/nutdrv_qx_voltronic.c
  drivers/nutdrv_siemens_sitop.c
  drivers/oneac.c
  drivers/optiups.c
  drivers/powercom.c
  drivers/powercom.h
  drivers/powerp-txt.c
  drivers/rhino.c
  drivers/safenet.c
  drivers/salicru-hid.c
  drivers/snmp-ups.c
  drivers/solis.c
  drivers/solis.h
  drivers/tripplite.c
  drivers/tripplite_usb.c
  drivers/victronups.c
  scripts/subdriver/gen-usbhid-subdriver.sh
  tools/nut-scanner/scan_snmp.c
Labels: CI, refactor/fightwarn

#1216 Fightwarn: huawei-ups2000
  drivers/huawei-ups2000.c
Labels: CI, refactor/fightwarn, modbus

#1217 CI: Small fixes to recipes and docs
  ci_build.sh
  common/Makefile.am
  docs/ci-farm-lxc-setup.txt
  docs/nut.dict
Labels: documentation, CI

#1219 Small recipe fixes
  Makefile.am
  ci_build.sh
Labels: CI

#1220 Update snmp-ups authproto/privproto docs
  docs/man/nut-scanner.txt
  docs/man/snmp-ups.txt
Labels: documentation, SNMP

#1221 CI: Improve ci_build.sh to help more in the Fightwarn cause
  ci_build.sh
  docs/developers.txt
Labels: CI

#1228 Add a short sleep between fallback instcmds in usbhid-ups.
  drivers/usbhid-ups.c
Labels: Tripp Lite, USB

#1226 Move check for LogMax encoding error to parsing of report description
  drivers/hidparser.c
Labels: USB

#1224 Add Powerwalker VFI 3000 TG Online UPS to driver.list.in
  data/driver.list.in
Labels: HCL, DDL

#1230 usbhid-ups: Add support for Delta/Minuteman UPS
  drivers/tripplite-hid.c
  scripts/upower/95-upower-hid.rules
Labels: USB

#1229 drivers/*_usb.c: fix whitespace (break long lines)
  drivers/blazer_usb.c
  drivers/nutdrv_qx.c
  drivers/richcomm_usb.c
  drivers/riello_usb.c
  drivers/usbhid-ups.c
  tools/nut-scanner/scan_usb.c
Labels: refactor/fightwarn

#1232 Fightwarn, style and CI recipe revisions
  Jenkinsfile-dynamatrix
  ci_build.sh
  common/common.c
  conf/upsmon.conf.sample.in
  configure.ac
  docs/developers.txt
  docs/nut.dict
  drivers/hidparser.c
  drivers/hidparser.h
  drivers/libhid.c
  drivers/libhid.h
  drivers/libshut.h
  drivers/libusb.h
  drivers/usbhid-ups.c
  include/nut_stdint.h
  m4/ax_c_pragmas.m4
  server/upsd.c
  tests/Makefile.am
Labels: CI, refactor/fightwarn

#1234 libusb 1.0+0.1 resync from master as of 2021-12-21
  Jenkinsfile-dynamatrix
  ci_build.sh
  common/common.c
  conf/upsmon.conf.sample.in
  configure.ac
  data/driver.list.in
  docs/developers.txt
  docs/man/nut-scanner.txt
  docs/man/snmp-ups.txt
  docs/nut.dict
  drivers/blazer_usb.c
  drivers/hidparser.c
  drivers/hidparser.h
  drivers/libhid.c
  drivers/libhid.h
  drivers/libshut.h
  drivers/nut_libusb.h
  drivers/nutdrv_qx.c
  drivers/richcomm_usb.c
  drivers/riello_usb.c
  drivers/tripplite-hid.c
  drivers/tripplite_usb.c
  drivers/usbhid-ups.c
  include/nut_stdint.h
  m4/ax_c_pragmas.m4
  scripts/upower/95-upower-hid.rules
  server/upsd.c
  tests/Makefile.am
  tests/getvaluetest.c
  tools/nut-scanner/scan_usb.c
Labels: USB, CI

#1244 Fightwarn libusb 1.0+0.1 rebased part1
  configure.ac
  docs/configure.txt
  drivers/Makefile.am
  drivers/bcmxcp_usb.c
  drivers/blazer_usb.c
  drivers/libhid.h
  drivers/libshut.c
  drivers/libshut.h
  drivers/libusb1.c
  drivers/nut_libusb.h
  drivers/nutdrv_atcl_usb.c
  drivers/nutdrv_qx.c
  drivers/richcomm_usb.c
  drivers/riello.h
  drivers/riello_usb.c
  drivers/tripplite_usb.c
  drivers/usb-common.h
  drivers/usbhid-ups.c
  m4/nut_check_libusb.m4
  tools/nut-scanner/nutscan-init.c
  tools/nut-scanner/scan_usb.c
  tools/nut-usbinfo.pl
Labels: USB, CI, refactor/fightwarn

#1243 Fightwarn libusb 1.0 rebased part1
  configure.ac
  drivers/Makefile.am
  drivers/bcmxcp_usb.c
  drivers/blazer_usb.c
  drivers/libhid.h
  drivers/libshut.c
  drivers/libshut.h
  drivers/libusb1.c
  drivers/nut_libusb.h
  drivers/nutdrv_atcl_usb.c
  drivers/nutdrv_qx.c
  drivers/richcomm_usb.c
  drivers/riello.h
  drivers/riello_usb.c
  drivers/tripplite_usb.c
  drivers/usb-common.h
  drivers/usbhid-ups.c
  m4/nut_check_libusb.m4
  tools/nut-scanner/nutscan-init.c
  tools/nut-scanner/scan_usb.c
  tools/nut-usbinfo.pl
Labels: USB, CI, refactor/fightwarn

#1248 docs/ci-farm-lxc-setup.txt: clarify how to find defined LXC templates and install CentOS on Debian host
  docs/ci-farm-lxc-setup.txt
  docs/config-prereqs.txt
  docs/nut.dict
Labels: documentation, CI

#1237 Revise nut-scanner logging
  clients/upsclient.c
  tools/nut-scanner/scan_ipmi.c
  tools/nut-scanner/scan_snmp.c
Labels: nut-scanner, refactor/fightwarn
