Repository networkupstools/nut, pull requests merged in 2022-08, with the labels that each got.

#1536 Fix case for EATON manufacturer
  drivers/mge-mib.c
Labels: Eaton, SNMP

#1532 Refactor fcntl(..., FD_CLOEXEC) as set_close_on_exec() where possible
  clients/upsmon.c
  clients/upssched.c
  common/common.c
  common/parseconf.c
  include/common.h
Labels: Windows, refactor/fightwarn

#1531 drivers/libusb.h, libshut.h, nutdrv_qx et al: rename open/close fields
  drivers/blazer_usb.c
  drivers/libshut.h
  drivers/nut_libusb.h
  drivers/nutdrv_qx.c
  drivers/riello_usb.c
  drivers/tripplite_usb.c
  drivers/usbhid-ups.c
Labels: Windows, refactor/fightwarn, serial port

#1530 Modbus drivers: fix to use `uint16_t` and `unsigned int`
  drivers/adelsystem_cbi.c
  drivers/generic_modbus.c
Labels: refactor/fightwarn, modbus

#1529 Define a NOTIFY_DEFAULT flag, use it to initialize upsmon.
  clients/upsmon.h
Labels: refactor/fightwarn

#1528 Rename some macros to avoid clashes with WIN32 build environment
  drivers/adelsystem_cbi.c
  drivers/adelsystem_cbi.h
  drivers/mge-xml.c
  drivers/netxml-ups.c
  drivers/netxml-ups.h
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx.h
  drivers/nutdrv_qx_bestups.c
  drivers/tripplitesu.c
  drivers/usbhid-ups.c
  drivers/usbhid-ups.h
Labels: Windows, refactor/fightwarn

#1527 common/common.c: refactor single get_libname_in_dir() from loop of get_libname()
  common/common.c
  configure.ac
Labels: refactor/fightwarn

#1537 Fix whitespace and some comments
  clients/upsclient.c
  clients/upsmon.c
  clients/upssched.c
  common/common.c
  common/snprintf.c
  docs/man/ups.conf.txt
  docs/nut.dict
  drivers/blazer_usb.c
  drivers/clone-outlet.c
  drivers/genericups.c
  drivers/isbmex.c
  drivers/libhid.h
  drivers/libshut.c
  drivers/snmp-ups.c
  drivers/usbhid-ups.c
  include/str.h
  server/upsd.c
  tools/nut-scanner/nutscan-serial.c
  tools/nut-scanner/scan_avahi.c
  tools/nut-scanner/scan_ipmi.c
  tools/nut-scanner/scan_nut.c
  tools/nut-scanner/scan_snmp.c
  tools/nut-scanner/scan_usb.c
  tools/nut-scanner/scan_xml_http.c
Labels: refactor/fightwarn

#1544 tools/nut-scanner/scan_usb.c: move "Clear any existing error" up…
  tools/nut-scanner/scan_usb.c
Labels: nut-scanner, USB, refactor/fightwarn

#1543 Fix typos
  configure.ac
  server/netssl.c
Labels: refactor/fightwarn

#1542 common/common.c: refactor confpath() and dflt_statepath()
  common/common.c
Labels: refactor/fightwarn

#1545 OpenBSD CI worker comments
  docs/config-prereqs.txt
  docs/nut.dict
Labels: documentation, CI

#1525 Windows v2.8.0 branch update to minimize differences vs. Master branch (and apply some fixes from it)
  .gitattributes
  .gitignore
  ci_build.sh
  clients/Makefile.am
  clients/upslog.c
  clients/upsmon.c
  clients/upssched.c
  common/common.c
  common/snprintf.c
  common/wincompat.c
  configure.ac
  docs/config-prereqs.txt
  docs/man/ups.conf.txt
  docs/nut.dict
  drivers/al175.c
  drivers/apcupsd-ups.c
  drivers/bcmxcp.c
  drivers/bcmxcp_ser.c
  drivers/bcmxcp_usb.c
  drivers/belkinunv.c
  drivers/clone-outlet.c
  drivers/clone.c
  drivers/dstate.h
  drivers/gamatronic.c
  drivers/genericups.h
  drivers/isbmex.c
  drivers/libusb1.c
  drivers/optiups.c
  drivers/powercom.c
  drivers/powerp-bin.c
  drivers/powerp-txt.c
  drivers/snmp-ups.c
  drivers/tripplite_usb.c
  drivers/upsdrvctl.c
  drivers/usbhid-ups.c
  include/common.h
  include/wincompat.h
  m4/nut_check_libltdl.m4
  scripts/Windows/README
  server/netssl.c
  server/sstate.c
  server/upsd.c
  tests/NIT/nit.sh
  tools/nut-scanner/scan_eaton_serial.c
  tools/nut-scanner/scan_nut.c
  tools/nut-scanner/scan_snmp.c
  tools/nut-scanner/scan_xml_http.c
Labels: Windows, refactor/fightwarn

#1524 Master branch update to minimize differences vs. Windows branch (and apply some fixes from it)
  autogen.sh
  clients/upssched.c
  common/atexit.c
  common/common.c
  common/parseconf.c
  common/setenv.c
  common/strerror.c
  drivers/apcupsd-ups.c
  drivers/dstate.c
  drivers/dummy-ups.c
  drivers/mge-hid.c
  drivers/serial.h
  drivers/snmp-ups.h
  include/proto.h
  m4/ax_c_pragmas.m4
  scripts/Windows/halt.c
Labels: Windows, refactor/fightwarn

#1548 Extend shared library-finding method and use-case to raise chances of success
  NEWS
  common/common.c
  docs/nut.dict
  tools/nut-scanner/nutscan-init.c
Labels: enhancement, refactor/fightwarn

#1549 scripts/Solaris/Makefile.am: do not install Solaris init files uninvited
  scripts/Solaris/Makefile.am
Labels: CI, refactor/fightwarn

#1546 Windows v2.8.0 branch update to minimize differences vs. Master branch (and apply some fixes from it) again
  Jenkinsfile-dynamatrix
  NEWS
  clients/upsmon.c
  clients/upssched.c
  common/common.c
  common/strptime.c
  docs/config-prereqs.txt
  docs/nut.dict
  drivers/huawei-ups2000.c
  drivers/mge-mib.c
  include/common.h
  include/nut_stdint.h
  scripts/Solaris/Makefile.am
  scripts/Windows/README
  scripts/Windows/build-mingw-nut.sh
  server/upsd.c
  tools/nut-scanner/nutscan-init.c
Labels: Windows, refactor/fightwarn

#1555 Windows v2.8.0 branch clean-up
  INSTALL.nut
  common/common.c
  configure.ac
  drivers/apcsmart.c
  drivers/belkinunv.c
  drivers/serial.c
  scripts/Windows/README
  server/sstate.c
  server/upsd.c
  tools/nut-scanner/nutscan-ip.h
  tools/nut-scanner/scan_eaton_serial.c
  tools/nut-scanner/scan_usb.c
  tools/nut-scanner/scan_xml_http.c
Labels: Windows, refactor/fightwarn

#1557 Fix file-descriptor type mess
  clients/upssched.c
  clients/upssched.h
  drivers/apcsmart.c
  drivers/belkinunv.c
  drivers/clone-outlet.c
  drivers/clone.c
  drivers/dstate.c
  drivers/dstate.h
  drivers/dummy-ups.c
  drivers/libhid.h
  drivers/libshut.c
  drivers/libshut.h
  drivers/main.c
  drivers/main.h
  drivers/serial.c
  drivers/serial.h
  include/common.h
  server/nut_ctype.h
  server/sstate.c
  server/sstate.h
  server/stype.h
  server/upsd.c
  server/upstype.h
  tools/nut-scanner/scan_eaton_serial.c
Labels: bug, Windows, refactor/fightwarn

#1561 More cleanup after Fix TYPE_FD mess
  UPGRADING
  clients/upssched.c
  drivers/dstate.c
  include/common.h
Labels: documentation, Windows, refactor/fightwarn

#1570 Some fixes for Solaris/illumos packaging and SMF support
  NEWS
  configure.ac
  scripts/Solaris/Makefile.am
  scripts/Solaris/nut-driver.xml.in
  scripts/Solaris/nut-server.xml.in
  scripts/Solaris/svc-nut-server.in
Labels: solaris

#1572 scripts/python/app/NUT-Monitor-py3qt5.in: fix __find_icon_file()...
  scripts/python/app/NUT-Monitor-py3qt5.in
Labels: python

#1573 Fix PyNUT ListClients() and DeviceLogin(), and nutclient (C++) equivalents
  NEWS
  clients/nutclient.cpp
  clients/nutclient.h
  clients/nutclientmem.cpp
  clients/nutclientmem.h
  docs/net-protocol.txt
  docs/nut.dict
  scripts/python/module/PyNUT.py.in
  scripts/python/module/README
  scripts/python/module/test_nutclient.py.in
  tests/NIT/nit.sh
  tests/cpputest-client.cpp
Labels: bug, C++, CI, python

#1576 Fix PyNUT ListClients() and DeviceLogin() for Python 3 string API
  scripts/python/module/PyNUT.py.in
  scripts/python/module/README
  tests/NIT/nit.sh
Labels: CI, python

#1575 Add a `usbhid-ups` driver option to toggle report descriptor fixup activation
  docs/man/usbhid-ups.txt
  drivers/apc-hid.c
  drivers/cps-hid.c
  drivers/usbhid-ups.c
  drivers/usbhid-ups.h
Labels: enhancement, need testing, USB, USB-HID encoding/LogMin/LogMax

#1578 m4/nut_check_libltdl.m4: fall back to /usr/local/... (e.g. on FreeBSD)…
  NEWS
  m4/nut_check_libltdl.m4
Labels: packaging, FreeBSD, CI

#1580 Windows v2.8.0 branch update to minimize differences with master and bring some test fixes from it
  NEWS
  UPGRADING
  ci_build.sh
  clients/nutclient.cpp
  clients/nutclient.h
  clients/nutclientmem.cpp
  clients/nutclientmem.h
  configure.ac
  docs/config-prereqs.txt
  docs/man/usbhid-ups.txt
  docs/net-protocol.txt
  docs/nut.dict
  docs/packager-guide.txt
  drivers/apc-hid.c
  drivers/cps-hid.c
  drivers/ietf-mib.c
  drivers/usbhid-ups.c
  drivers/usbhid-ups.h
  m4/nut_arg_with.m4
  m4/nut_check_libltdl.m4
  scripts/Solaris/Makefile.am
  scripts/Solaris/nut-driver.xml.in
  scripts/Solaris/nut-server.xml.in
  scripts/Solaris/svc-nut-server.in
  scripts/python/app/NUT-Monitor-py3qt5.in
  scripts/python/module/PyNUT.py.in
  scripts/python/module/README
  scripts/python/module/test_nutclient.py.in
  tests/NIT/nit.sh
  tests/cpputest-client.cpp
  tools/nut-scanner/Makefile.am
Labels: Windows, CI

#1582 snmp-ups: fix alarm processing
  drivers/snmp-ups.c
Labels: SNMP

#1586 PY say NO!
  m4/nut_check_python.m4
Labels: bug, packaging, CI, python

#1581 CI: Set up regular native (MSYS2/MinGW) NUT for Windows builds with AppVeyor
  INSTALL.nut
  Makefile.am
  NEWS
  appveyor.yml
  ci_build.sh
  docs/nut.dict
  m4/nut_check_python.m4
  scripts/Windows/build-mingw-nut.sh
  scripts/Windows/dllldd.sh
Labels: documentation, Windows, CI, python

#1595 Blazer: Accept the value of "idleload" equal to zero
  drivers/blazer.c
Labels: Qx protocol driver

#1591 common/common.c: avoid realpath() on platforms that lack it
  common/common.c
Labels: refactor/fightwarn

#1597 Windows v2.8.0 branch cleanup
  appveyor.yml
  clients/nutclient.cpp
  clients/upssched.c
  common/Makefile.am
  configure.ac
  drivers/apcupsd-ups.c
  drivers/dstate.c
  drivers/netxml-ups.c
  drivers/riello_ser.c
  m4/nut_check_libnetsnmp.m4
  server/conf.c
  tools/nut-scanner/Makefile.am
Labels: Windows, refactor/fightwarn

#1596 Fix Windows v2.8.0 C++11 and cppunit builds
  Jenkinsfile-dynamatrix
  appveyor.yml
  ci_build.sh
  clients/Makefile.am
  clients/nutclient.cpp
  clients/nutclient.h
  clients/nutclientmem.cpp
  common/snprintf.c
  docs/config-prereqs.txt
  include/timehead.h
  m4/nut_check_libnetsnmp.m4
  scripts/Windows/build-mingw-nut.sh
  scripts/Windows/dllldd.sh
  tests/NIT/Makefile.am
  tests/NIT/nit.sh
  tools/nut-scanner/Makefile.am
Labels: C++, Windows

#1607 Update Windows branch from master, as of 2022-08-22
  drivers/blazer.c
Labels: Windows

#1612 Bump CI and test scripts
  ci_build.sh
  configure.ac
  tests/NIT/Makefile.am
  tests/NIT/nit.sh
Labels: CI

#1616 Revise publicly distributed NUT headers (were generally neglected)
  clients/Makefile.am
  clients/nutclientmem.cpp
  include/Makefile.am
  tools/nut-scanner/nut-scan.h
  tools/nut-scanner/nutscan-ip.c
  tools/nut-scanner/scan_eaton_serial.c
  tools/nut-scanner/scan_nut.c
  tools/nut-scanner/scan_snmp.c
Labels: packaging, refactor/fightwarn

#1617 Revise PyNUT self-test to actually fail
  scripts/python/module/PyNUT.py.in
  scripts/python/module/README
  scripts/python/module/test_nutclient.py.in
  tests/NIT/nit.sh
Labels: CI, python

#1615 Revise man pages (for Windows branch changes) and distributed headers (were generally neglected)
  clients/Makefile.am
  clients/nutclientmem.cpp
  docs/new-drivers.txt
  docs/nut.dict
  drivers/serial.c
  drivers/serial.h
  include/Makefile.am
  scripts/Windows/build-mingw-nut.sh
  tools/nut-scanner/nut-scan.h
  tools/nut-scanner/nutscan-ip.c
  tools/nut-scanner/nutscan-ip.h
  tools/nut-scanner/scan_eaton_serial.c
  tools/nut-scanner/scan_nut.c
  tools/nut-scanner/scan_snmp.c
Labels: packaging, documentation, Windows, refactor/fightwarn

#1621 Resync Windows v2.8.0 branch from master yet again
  NEWS
  docs/config-prereqs.txt
  include/Makefile.am
  scripts/Windows/README
  scripts/python/module/PyNUT.py.in
  scripts/python/module/README
  scripts/python/module/test_nutclient.py.in
  tests/NIT/nit.sh
Labels: Windows, CI

#1635 Update gen-usbhid-subdriver.sh and docs/hid-subdrivers.txt
  docs/hid-subdrivers.txt
  docs/nut.dict
  scripts/subdriver/gen-usbhid-subdriver.sh
Labels: enhancement, documentation

#1633 common/common.c: get_libname_in_dir(): check for exact filename match…
  common/common.c
Labels: bug

#1631 Be sure to (eventually) disconnect upsd from dead drivers
  NEWS
  docs/nut.dict
  drivers/dstate.c
  server/sstate.c
Labels: bug

#1636 Windows branch: fix builds against libusb-win32
  drivers/usb-common.h
  m4/nut_check_libusb.m4
  tools/nut-usbinfo.pl
Labels: Windows, refactor/fightwarn

#1628 configure.ac, drivers/libusb0.c: fix detection of strlwr() and fallback strcasestr() implem
  configure.ac
  drivers/libusb0.c
Labels: bug, Windows, CI

#1632 usbhid-ups: do not crash due to auto-reconnecting
  drivers/usbhid-ups.c
Labels: bug

#1637 upslog: Messages should go to syslog
  clients/upslog.c
Labels: ready / gonna merge

#1641 Further revise NUT public API headers
  NEWS
  UPGRADING
  clients/Makefile.am
  clients/upsclient.h
  include/Makefile.am
  include/parseconf.h
  tools/nut-scanner/Makefile.am
  tools/nut-scanner/nut-scan.h
Labels: bug, refactor/fightwarn
