Repository networkupstools/nut, pull requests merged in 2022-12, with the labels that each got.

#1722 Update mge-hid.c
  drivers/mge-hid.c
Labels: Eaton, USB

#1725 common/common.c: become_user(): cosmetic/messaging: discern starting …
  common/common.c
Labels: enhancement, service/daemon start/stop

#1724 Suggest in docs and daemon messages how command-signals vs. PID files vs. systemd units interact
  clients/upsmon.c
  common/common.c
  conf/ups.conf.sample
  conf/upsd.users.sample
  conf/upsmon.conf.sample.in
  configure.ac
  docs/FAQ.txt
  docs/config-notes.txt
  docs/man/upsd.txt
  scripts/systemd/nut-server.service.in
  server/upsd.c
Labels: enhancement, documentation, service/daemon start/stop, Linux

#1734 Fix discovery issue with Eaton pdu nlogic
  drivers/eaton-pdu-nlogic-mib.c
Labels: bug, Eaton, SNMP

#1748 Speed bump for laggy CI
  ci_build.sh
  tests/NIT/nit.sh
Labels: CI

#1743 Update gitlog2changelog for python-3.6
  tools/gitlog2changelog.py.in
Labels: bug, documentation, CI, python

#1742 Introduce WITH_UNMAPPED_DATA_POINTS for USB-HID and SNMP subdrivers
  NEWS
  configure.ac
  docs/configure.txt
  docs/hid-subdrivers.txt
  docs/snmp-subdrivers.txt
  drivers/apc-ats-mib.c
  drivers/apc-epdu-mib.c
  drivers/apc-mib.c
  drivers/apc-pdu-mib.c
  drivers/belkin-hid.c
  drivers/compaq-mib.c
  drivers/cps-hid.c
  drivers/delta_ups-mib.c
  drivers/eaton-ats16-nm2-mib.c
  drivers/eaton-ats16-nmc-mib.c
  drivers/eaton-ats30-mib.c
  drivers/eaton-pdu-marlin-mib.c
  drivers/eaton-pdu-nlogic-mib.c
  drivers/emerson-avocent-pdu-mib.c
  drivers/ever-hid.c
  drivers/hpe-pdu-mib.c
  drivers/hpe-pdu3-cis-mib.c
  drivers/huawei-mib.c
  drivers/idowell-hid.c
  drivers/liebert-hid.c
  drivers/powercom-hid.c
  drivers/raritan-px2-mib.c
  drivers/tripplite-hid.c
  scripts/subdriver/gen-snmp-subdriver.sh
  scripts/subdriver/gen-usbhid-subdriver.sh
Labels: enhancement, SNMP, USB, CI

#1738 Fix some problems building recent NUT on Solaris 8
  NEWS
  autogen.sh
  common/Makefile.am
  common/common.c
  common/snprintf.c
  common/strnlen.c
  common/strptime.c
  configure.ac
  drivers/adelsystem_cbi.h
  drivers/eaton-pdu-marlin-helpers.c
  drivers/mge-hid.c
  drivers/pijuice.c
  drivers/riello.c
  drivers/riello.h
  drivers/riello_ser.c
  drivers/riello_usb.c
  include/common.h
  m4/nut_check_python.m4
  scripts/augeas/Makefile.am
  tests/.gitignore
  tests/Makefile.am
  tests/NIT/nit.sh
  tests/getvaluetest.c
  tests/nutlogtest.c
  tools/Makefile.am
  tools/nut-scanner/Makefile.am
  tools/nut-usbinfo.pl
Labels: CI, refactor/fightwarn, solaris
