Repository networkupstools/nut, pull requests merged in 2023-03, with the labels that each got.

#1864 Add debug verbosity setting for upssched, add `upsdebugx` for `parse_at()`, and add help lines for `-h/-V` in many tools
  clients/upsc.c
  clients/upscmd.c
  clients/upslog.c
  clients/upsmon.c
  clients/upsrw.c
  clients/upssched.c
  docs/developers.txt
  server/upsd.c
  tools/nut-scanner/nut-scanner.c
Labels: enhancement, documentation

#1866 Fix some runtime issues seen on Windows
  ci_build.sh
  common/common.c
  drivers/libusb1.c
  tools/nut-scanner/nutscan-init.c
  tools/nut-scanner/scan_ipmi.c
  tools/nut-scanner/scan_snmp.c
  tools/nut-scanner/scan_usb.c
  tools/nut-scanner/scan_xml_http.c
Labels: bug, Windows, nut-scanner

#1870 Docs: touch on IDE support
  ci_build.sh
  docs/developers.txt
  docs/nut.dict
Labels: documentation

#1855 Adding GPIO interface
  NEWS
  UPGRADING
  configure.ac
  docs/config-prereqs.txt
  docs/configure.txt
  docs/man/Makefile.am
  docs/man/generic_gpio.txt
  docs/nut.dict
  docs/packager-guide.txt
  drivers/Makefile.am
  drivers/dstate.c
  drivers/generic_gpio_common.c
  drivers/generic_gpio_common.h
  drivers/generic_gpio_libgpiod.c
  drivers/generic_gpio_libgpiod.h
  drivers/main.c
  drivers/main.h
  m4/nut_check_libgpiod.m4
  tests/.gitignore
  tests/Makefile.am
  tests/generic_gpio_liblocal.c
  tests/generic_gpio_test.txt
  tests/generic_gpio_utest.c
  tests/generic_gpio_utest.h
Labels: feature, GPIO

#1875 fix upsdrvctl behavior in foregrounding mode
  NEWS
  docs/man/upsdrvctl.txt
  drivers/upsdrvctl.c
  tests/NIT/nit.sh
Labels: bug, packaging, need testing, ready / gonna merge, service/daemon start/stop

#1885 C++11 support tighter check
  clients/nutclient.cpp
  clients/nutclient.h
  configure.ac
Labels: C++, portability

#1888 Allow verbose autogen.sh; improve build recipe portability
  .gitignore
  Makefile.am
  autogen.sh
  configure.ac
Labels: CI, portability

#1889 FDs 0,1,2 are not always STDIO
  common/common.c
  configure.ac
  include/common.h
Labels: ready / gonna merge, portability
