Repository networkupstools/nut, pull requests merged in 2023-06, with the labels that each got.

#1945 Some small enhancements on gitlog2changelog.py
  tools/gitlog2changelog.py.in
Labels: enhancement, CI, ready / gonna merge

#1955 tools/gitlog2changelog.py.in: update TextWrapper settings to not break up file paths
  NEWS
  UPGRADING
  tools/gitlog2changelog.py.in
Labels: enhancement, CI

#1959 Fix documentation references to `_status_data`
  docs/man/upslog.txt
  docs/nut-names.txt
Labels: documentation

#1968 Improved Phoenixtec 0x06DA:0xFFFF support
  drivers/liebert-hid.c
Labels: USB, experimental-namespace, PowerWalker

#1965 Avoid `upssched` infinite tight loops with (probably) closed sockets
  NEWS
  clients/upssched.c
  docs/man/upssched.txt
Labels: bug, ready / code review, upssched
