Repository networkupstools/nut, pull requests merged in 2023-10, with the labels that each got.

#2082 `nut-scanner`: additional multiarch libraries search path; general: fixes to (debug) logging
  NEWS.adoc
  UPGRADING.adoc
  common/common.c
  configure.ac
  include/common.h
  tests/NIT/nit.sh
  tools/nut-scanner/Makefile.am
  tools/nut-scanner/nut-scanner.c
  tools/nut-scanner/nutscan-init.c
  tools/nut-scanner/nutscan-ip.c
Labels: bug, enhancement, Windows, nut-scanner, portability

#2086 docs/Makefile.am: avoid defining "check-local" target twice…
  docs/Makefile.am
Labels: bug, CI, portability

#2088 configure.ac: Fix out of source tree builds
  configure.ac
Labels: bug, packaging, CI, portability

#2085 systemd integration update and nut.conf comments
  clients/Makefile.am
  common/common.c
  conf/nut.conf.sample
  configure.ac
  docs/configure.txt
  docs/man/nut.conf.txt
  docs/nut.dict
  scripts/systemd/nut-driver-enumerator.path.in
  scripts/systemd/nut-driver-enumerator.service.in
  scripts/systemd/nut-driver.target
  scripts/systemd/nut-driver@.service.in
  scripts/systemd/nut-monitor.service.in
  scripts/systemd/nut-server.service.in
  scripts/systemd/nut.target
  scripts/systemd/nutshutdown.in
Labels: enhancement, packaging, documentation, systemd, ready / gonna merge, Shutdowns and overrides and battery level triggers

#2089 Correct voltage and battery capacity for Opti-UPS 230VAC and/or 24VDC models
  NEWS.adoc
  data/driver.list.in
  drivers/optiups.c
Labels: enhancement

#2091 Fix docs makefiles
  docs/Makefile.am
  docs/man/Makefile.am
Labels: bug, packaging, CI, portability

#2096 A little bit of Fightwarn
  Jenkinsfile-dynamatrix
  clients/upsclient.c
  clients/upssched.c
  common/common.c
  common/wincompat.c
  configure.ac
  data/driver.list.in
  drivers/apcupsd-ups.c
  drivers/clone.c
  drivers/dummy-ups.c
  drivers/main.c
  drivers/upsdrvquery.c
  include/wincompat.h
  m4/ax_c_pragmas.m4
  m4/ax_run_or_link_ifelse.m4
  server/netssl.c
  tests/Makefile.am
  tests/generic_gpio_utest.c
  tests/nutlogtest.c
  tools/nut-scanner/scan_xml_http.c
Labels: enhancement, CI, refactor/fightwarn, portability

#2098 Fix issues in compaq mib
  drivers/compaq-mib.c
Labels: bug, SNMP, impacts-release-2.8.0

#2102 tripplite_usb.c Enhanced Device Identification in the tripplite_usb Driver for Tripp Lite USB UPSes
  NEWS.adoc
  docs/man/tripplite_usb.txt
  docs/nut.dict
  drivers/tripplite_usb.c
Labels: enhancement, Tripp Lite, USB, USB-duplicate-devices, impacts-release-2.8.0

#2090 add support to SMS 1phase brazil from #1987
  NEWS.adoc
  docs/man/Makefile.am
  docs/man/sms_ser.txt
  docs/nut.dict
  docs/sms-brazil-protocol.txt
  drivers/Makefile.am
  drivers/sms_ser.c
  drivers/sms_ser.h
Labels: enhancement, Qx protocol driver, serial port, ViewPower

#2111 Fix loss of configure-phase detection due to recent enhancements
  configure.ac
  include/str.h
  m4/ax_c_pragmas.m4
  m4/ax_run_or_link_ifelse.m4
  tests/Makefile.am
Labels: bug, CI, refactor/fightwarn, portability

#2113 data/cmdvartab: define descriptions for recently added…
  data/cmdvartab
Labels: enhancement, documentation

#2114 drivers/libusb1.c: nut_libusb_open(): do not keep Bus/Device/BusPort…
  drivers/libusb1.c
Labels: bug, USB, impacts-release-2.8.0

#2116 configure.ac: relax the check warning for gmtime_[rs] and localtime_[rs]…
  configure.ac
Labels: enhancement, packaging, CI, portability

#2063 apc_modbus: Support for APC Modbus protocol
  AUTHORS
  data/driver.list.in
  docs/man/Makefile.am
  docs/man/apc_modbus.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/apc_modbus.c
  m4/nut_check_libmodbus.m4
  tools/nut-usbinfo.pl
Labels: enhancement, APC, USB, ready / gonna merge, modbus, serial port, documentation-protocol

#2117 Follow-up for `apc_modbus` driver
  NEWS.adoc
  scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
Labels: documentation, systemd, nut-driver-enumerator (NDE)

#2123 apc_modbus: Use snprintf instead of strncpy
  drivers/apc_modbus.c
Labels: enhancement, ready / gonna merge, refactor/fightwarn

#2124 Add `SIZEOF_ARRAY` macro and use where applicable
  drivers/apc_modbus.c
  drivers/apcsmart.c
  drivers/belkinunv.c
  drivers/openups-hid.c
  drivers/optiups.c
  drivers/tripplitesu.c
  include/common.h
  tests/getvaluetest.c
Labels: enhancement, ready / gonna merge, refactor/fightwarn

#2129 CI: Apply github notifications and JSL loading enhancements from Fightwarn branch
  Jenkinsfile-dynamatrix
Labels: CI

#2127 upsmon: fix discrepancies between linestate & status flags resulting in critical UPS
  clients/upsmon.c
Labels: bug, enhancement, upsmon, Shutdowns and overrides and battery level triggers

#2131 drivers/apcsmart-old.c: do_capabilities(): revert to behavior like in…
  drivers/apcsmart-old.c
  drivers/apcsmart.c
Labels: bug, APC, impacts-release-2.8.0

#2132 dummy-ups: relax error handling to prevent premature driver termination
  NEWS.adoc
  docs/man/dummy-ups.txt
  drivers/dummy-ups.c
Labels: enhancement, service/daemon start/stop

#2133 clients/upsmon.c et al: introduce SHUTDOWNEXIT boolean/delay-length option [#2133]
  NEWS.adoc
  clients/upsmon.c
  conf/upsmon.conf.sample.in
  docs/man/upsmon.conf.txt
  docs/nut.dict
Labels: enhancement, service/daemon start/stop, upsmon, Shutdowns and overrides and battery level triggers

#2135 `upsdrvctl`: separate `exec_timeout` from `exec_error`
  drivers/upsdrvctl.c
Labels: service/daemon start/stop

#2136 Introduce `NUT_QUIET_INIT_UPSNOTIFY=true` support
  NEWS.adoc
  common/common.c
  docs/nut.dict
  scripts/Aix/nut.init.in
  scripts/HP-UX/nut-drvctl.sh
  scripts/HP-UX/nut-upsd.sh
  scripts/HP-UX/nut-upsmon.sh
  scripts/RedHat/upsd.in
  scripts/RedHat/upsmon.in
  scripts/Solaris/nut.in
  scripts/Solaris/svc-nut-monitor.in
  scripts/Solaris/svc-nut-server.in
  scripts/Solaris8/S99upsmon
Labels: enhancement, packaging, portability

#2138 drivers/riello*.c: fix back bit maths changed with #1106
  NEWS.adoc
  drivers/riello.c
  drivers/riello_ser.c
  drivers/riello_usb.c
Labels: bug, USB, serial port, Riello, impacts-release-2.8.0

#2141 Update a few NUT for Windows documents and scripts
  INSTALL.nut.adoc
  NEWS.adoc
  appveyor.yml
  ci_build.sh
  configure.ac
  docs/config-prereqs.txt
  scripts/Windows/Installer/.gitignore
  scripts/Windows/Installer/NUT-Installer.xml.in
  scripts/Windows/Installer/README.adoc
  scripts/Windows/Makefile.am
  scripts/Windows/README.adoc
  scripts/Windows/build-mingw-nut.sh
  scripts/Windows/build-mingw-prereqs.sh
Labels: documentation, Windows, CI
