Repository networkupstools/nut, pull requests merged in 2023-02, with the labels that each got.

#1845 INSTALL.nut: update with "in-place" rebuilds chapter [#1826]
  INSTALL.nut
  docs/nut.dict
Labels: documentation

#1847 huawei-ups2000: fix broken timeout recovery behavior in Issue #1846.
  drivers/huawei-ups2000.c
Labels: modbus

#1850 Fixes for unreadable "inplace" sysconfdir, and exclusive '-a id'/'-s id' for drivers
  configure.ac
  drivers/main.c
Labels: bug

#1848 add support for minuteman device PRO1500RT2U (a0a0)
  drivers/tripplite-hid.c
  scripts/upower/95-upower-hid.hwdb
Labels: USB

#1854 Debug `nut_report_config_flags()`: report version from AC_INIT vs. Git revision (if available) and compiler version
  common/common.c
  configure.ac
  m4/nut_compiler_family.m4
  m4/nut_report_feature.m4
Labels: enhancement, packaging, CI
