Repository networkupstools/nut, pull requests merged in 2024-05, with the labels that each got.

#2425 Update `nutconf` and `augeas` lenses with support for NUT keywords added between releases 2.6.5 and 2.8.2
  NEWS.adoc
  common/nutconf.cpp
  common/nutwriter.cpp
  conf/nut.conf.sample
  docs/man/nut.conf.txt
  docs/nut.dict
  drivers/blazer.c
  drivers/blazer_ser.c
  drivers/blazer_usb.c
  drivers/nut-ipmipsu.c
  include/nutconf.hpp
  include/nutwriter.hpp
  scripts/augeas/Makefile.am
  scripts/augeas/gen-nutupsconf-aug.py.in
  scripts/augeas/nutnutconf.aug.in
  scripts/augeas/nutupsconf.aug.tpl
  scripts/augeas/nutupsdconf.aug.in
  scripts/augeas/nutupsdusers.aug.in
  scripts/augeas/nutupsmonconf.aug.in
  scripts/augeas/tests/test_nut.aug
  scripts/augeas/tests/test_nut_fixme.aug
  scripts/augeas/tests/test_nut_flaky.aug
  tests/nutconf_parser_ut.cpp
  tests/nutconf_ut.cpp
  tools/nutconf/nutconf-cli.cpp
Labels: portability, nutconf, impacts-release-2.8.2, augeas

#2427 drivers/gamatronic.c: Replace strcpy() on overlapping strings, and ensure UPS-provided data length cannot overflow string buffer
  drivers/gamatronic.c
Labels: bug, impacts-release-2.8.2

#2434 Refine nutconf-related code about exceptional situations
  common/nutwriter.cpp
  include/nutconf.hpp
Labels: bug, C++, nutconf

#2438 error: template-id not allowed for destructor in C++20
  NEWS.adoc
  autogen.sh
  include/nutipc.hpp
  tools/nut-scanner/nutscan-display.c
  tools/nut-usbinfo.pl
Labels: bug, C++, refactor/fightwarn, portability

#2435 Regenerate `ChangeLog` file only if git metadata got updated
  Makefile.am
  docs/Makefile.am
Labels: enhancement, documentation, CI, refactor/fightwarn

#2428 `usbhid-ups.c`: complete the support of `onlinedischarge_log_throttle_hovercharge` setting
  NEWS.adoc
  drivers/usbhid-ups.c
Labels: enhancement, USB, Shutdowns and overrides and battery level triggers, impacts-release-2.8.2

#2430 New driver hwmon_ina219
  NEWS.adoc
  data/driver.list.in
  docs/man/Makefile.am
  docs/man/hwmon_ina219.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/hwmon_ina219.c
Labels: ready / gonna merge, Linux

#2442 `mge-hid.c`: extend `mge_model_names[]` for Eaton 5SC and 5PX series
  NEWS.adoc
  drivers/mge-hid.c
Labels: enhancement, need testing, Eaton, USB

#2446 WIN32: Document `nut.exe` wrapper and improve its usability
  NEWS.adoc
  docs/man/Makefile.am
  docs/man/nut.exe.txt
  scripts/Windows/wininit.c
Labels: enhancement, documentation, Windows

#2445 Enable installation of built HTML and PDF documents
  Makefile.am
  NEWS.adoc
  UPGRADING.adoc
  configure.ac
  docs/Makefile.am
  docs/man/Makefile.am
  docs/nut.dict
  scripts/Windows/build-mingw-nut.sh
  scripts/augeas/Makefile.am
Labels: enhancement, packaging, documentation, CI

#2449 `nut-scanner`: Fix "Old NUT" detection and clarify some log messages
  NEWS.adoc
  tools/nut-scanner/nut-scanner.c
  tools/nut-scanner/nutscan-init.c
Labels: bug, enhancement, nut-scanner, impacts-release-2.8.2

#2456 Add `net start/stop` docs and practical support to `nut.exe`
  docs/man/nut.exe.txt
  docs/nut.dict
  scripts/Windows/wininit.c
Labels: enhancement, Windows, impacts-release-2.8.2

#2459 bicker_ser: allow changing of non-volatile variables with `upsrw`
  docs/man/bicker_ser.txt
  drivers/bicker_ser.c
Labels: enhancement, serial port
