Repository networkupstools/nut, pull requests merged in 2024-06, with the labels that each got.

#2461 Introduce `NUT_DEBUG_SYSLOG` envvar to completely disable `syslog` (e.g. in NIT)
  NEWS.adoc
  common/common.c
  conf/nut.conf.sample
  docs/man/nut.conf.txt
  include/common.h
  tests/NIT/nit.sh
Labels: enhancement, need testing, systemd, CI, service/daemon start/stop

#2462 clients/upsmon: restore handling of comm failure while on battery
  NEWS.adoc
  clients/upsmon.c
Labels: bug, upsmon, Shutdowns and overrides and battery level triggers, impacts-release-2.8.2

#2471 Hardening: Fall-back double-`checkprocname()` vs. current daemon program name (and add `NUT_IGNORE_CHECKPROCNAME=true` toggle)
  NEWS.adoc
  UPGRADING.adoc
  clients/upsmon.c
  common/common.c
  conf/nut.conf.sample
  docs/man/nut.conf.txt
  docs/nut.dict
  drivers/main.c
  drivers/upsdrvctl.c
  include/common.h
  scripts/Windows/wininit.c
  server/upsd.c
Labels: enhancement, service/daemon start/stop, upsmon, portability, C-str

#2486 Make sure NUT driver daemons close their Unix sockets when their counterparts do
  NEWS.adoc
  clients/nutclient.h
  clients/nutclientmem.h
  clients/upsclient.h
  drivers/dstate.c
  drivers/dstate.h
  drivers/generic_gpio_common.h
  drivers/generic_gpio_libgpiod.h
  drivers/hidparser.h
  drivers/libhid.h
  drivers/main.h
  drivers/upsdrvquery.h
  server/upsd.h
  tests/NIT/nit.sh
Labels: bug, service/daemon start/stop, impacts-release-2.8.1, impacts-release-2.8.2

#2481 Combine several small PRs for issue #1316 and their NEWS entries
  Makefile.am
  NEWS.adoc
  common/Makefile.am
  configure.ac
  docs/configure.txt
  docs/nut.dict
  drivers/Makefile.am
  m4/ax_c_pragmas.m4
  tools/nut-scanner/Makefile.am
Labels: refactor/fightwarn, portability, DMF

#2478 common/Makefile.am, tools/nut-scanner/Makefile.am: Introduce `libcommonstr.la`
  common/Makefile.am
  tools/nut-scanner/Makefile.am
Labels: nut-scanner, refactor/fightwarn, DMF, C-str

#2477 m4/ax_c_pragmas.m4: introduce HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_ADDRESS and HAVE_PRAGMA_GCC_DIAGNOSTIC_IGNORED_PEDANTIC
  m4/ax_c_pragmas.m4
Labels: CI, portability, DMF

#2474 Define an `auglenstestsdir` to install the augeas `test_nut.aug` file
  configure.ac
  scripts/augeas/Makefile.am
Labels: CI, DMF, augeas

#2490 Port recipe for `libserial-nutscan.la` from DMF/FTY branch and clean up nut-scanner makefile
  drivers/Makefile.am
  tools/nut-scanner/Makefile.am
Labels: enhancement, nut-scanner, CI, DMF

#2475 clients/upsclient.h: include sys/types.h
  clients/upsclient.h
Labels: bug, portability, impacts-release-2.8.0, impacts-release-2.8.1, impacts-release-2.8.2

#2472 FTY remerge from master as of 2024-06-15
  NEWS.adoc
  README.adoc
  UPGRADING.adoc
  clients/nutclient.h
  clients/nutclientmem.h
  clients/upsclient.h
  clients/upsmon.c
  common/Makefile.am
  common/common.c
  conf/nut.conf.sample
  configure.ac
  data/driver.list.in
  docs/configure.txt
  docs/documentation.txt
  docs/man/Makefile.am
  docs/man/bicker_ser.txt
  docs/man/nut.conf.txt
  docs/man/nut.exe.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/bicker_ser.c
  drivers/dstate.c
  drivers/dstate.h
  drivers/generic_gpio_common.h
  drivers/generic_gpio_libgpiod.h
  drivers/hidparser.h
  drivers/libhid.h
  drivers/main.c
  drivers/main.h
  drivers/netxml-ups.c
  drivers/snmp-ups.c
  drivers/upsdrvctl.c
  drivers/upsdrvquery.h
  include/common.h
  scripts/Windows/wininit.c
  server/upsd.c
  server/upsd.h
  tests/NIT/nit.sh
  tools/nut-scanner/Makefile.am
Labels: DMF, nutconf, impacts-release-2.8.2
