Repository networkupstools/nut, pull requests merged in 2024-03, with the labels that each got.

#2333 docs/Makefile.am: reminder about missing dictionary when aspell is unavailable
  docs/Makefile.am
Labels: CI, portability, impacts-release-2.8.1

#2329 Conjure up `config.h` header guards and improve search for shared libs
  common/common.c
  conf/Makefile.am
  data/Makefile.am
  data/html/Makefile.am
  docs/config-prereqs.txt
  docs/man/Makefile.am
  drivers/hidparser.h
  drivers/libhid.h
  drivers/nutdrv_qx.h
  drivers/serial.h
  drivers/snmp-ups.h
  drivers/usb-common.h
  drivers/usbhid-ups.h
  include/common.h
  include/nut_float.h
  include/nut_stdint.h
  include/proto.h
  scripts/Makefile.am
  scripts/Solaris/Makefile.am
  scripts/Windows/Makefile.am
  scripts/devd/Makefile.am
  scripts/hotplug/Makefile.am
  scripts/installer/Makefile.am
  scripts/python/Makefile.am
  scripts/systemd/Makefile.am
  scripts/udev/Makefile.am
  scripts/upsdrvsvcctl/Makefile.am
  tests/NIT/Makefile.am
Labels: CI, refactor/fightwarn, portability

#2332 huawei-ups2000.txt: add UPS2000-G-3KRTL to the confirmed list
  docs/man/huawei-ups2000.txt
  docs/nut.dict
Labels: HCL, documentation, modbus, impacts-release-2.8.1

#2272 Update USB product IDs for Belkin/Liebert
  drivers/belkin-hid.c
  scripts/upower/95-upower-hid.hwdb
Labels: USB, liebert

#2331 Multiple USB-capable drivers: add ways to tune USB HID config, report, descriptor indexes and in/out endpoints
  NEWS.adoc
  conf/ups.conf.sample
  docs/man/nut_usb_addvars.txt
  docs/man/ups.conf.txt
  docs/nut.dict
  drivers/arduino-hid.c
  drivers/libshut.c
  drivers/libusb0.c
  drivers/libusb1.c
  drivers/main.c
  drivers/powervar-hid.c
  tools/nut-scanner/scan_usb.c
Labels: enhancement, USB, USB non-zero interface numbers

#2336 Fix `nut-scanner` caveats about USB optional fields and simulation file discovery
  tools/nut-scanner/nut-scanner.c
  tools/nut-scanner/scan_nut_simulation.c
Labels: bug, nut-scanner

#2184 apc_modbus: Updates, command, writable variables and outlet group support
  configure.ac
  drivers/Makefile.am
  drivers/apc_modbus.c
  drivers/apc_modbus.h
  drivers/upshandler.h
  include/timehead.h
Labels: enhancement, APC, modbus

#2345 Bump NUT `master` branch from FTY
  NEWS.adoc
  UPGRADING.adoc
  autogen.sh
  common/common.c
  docs/config-notes.txt
  docs/config-prereqs.txt
  docs/man/nut-scanner.txt
  drivers/dstate.c
  drivers/nut-libfreeipmi.c
  drivers/snmp-ups.c
  m4/ax_c_pragmas.m4
  scripts/systemd/.gitignore
  tools/nut-scanner/nut-scanner.c
  tools/nut-scanner/scan_snmp.c
  tools/nut-usbinfo.pl
Labels: enhancement, portability, DMF

#2346 Bump NUT `master` branch from FTY: systemd integration
  scripts/systemd/nut-driver-enumerator-daemon-activator.path.in
  scripts/systemd/nut-driver-enumerator-daemon-activator.service.in
  scripts/systemd/nut-server.service.in
Labels: enhancement, need testing, systemd, Linux, nut-driver-enumerator (NDE), Connection stability issues

#2350 [CI] .github/workflows/codeql.yml: extend with python
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: CI, python

#2354 .github/workflows/codeql.yml: fix stringification of "ubuntu-latest"
  .github/workflows/codeql.yml
Labels: CI

#2355 .github/workflows/codeql.yml: make a CodeQL matrix…
  .github/workflows/codeql.yml
Labels: CI, refactor/fightwarn

#2352 Update Jenkinsfile-dynamatrix
  Jenkinsfile-dynamatrix
Labels: CI

#2360 CI: Fix pure autoconf builds (CCACHE_DIR interaction) and some C/C++ warnings, and a `ChangeLog.pdf` fault on older systems
  Jenkinsfile-dynamatrix
  Makefile.am
  clients/Makefile.am
  common/Makefile.am
  common/nutstream.cpp
  configure.ac
  docs/Makefile.am
  drivers/Makefile.am
  include/Makefile.am
  lib/Makefile.am
  server/Makefile.am
  tests/Makefile.am
  tests/NIT/Makefile.am
  tools/Makefile.am
  tools/gitlog2changelog.py.in
  tools/nut-scanner/Makefile.am
  tools/nutconf/Makefile.am
Labels: C++, CI, refactor/fightwarn, nutconf

#2363 Extend `nutconf` vocabulary
  common/nutconf.cpp
  common/nutwriter.cpp
  include/nutconf.hpp
  tests/nutconf_parser_ut.cpp
  tests/nutconf_ut.cpp
  tools/nutconf/nutconf-cli.cpp
Labels: enhancement, nutconf

#2364 Installer revise
  docs/nut.dict
  scripts/installer/Makefile.am
  scripts/installer/README.adoc
  scripts/installer/make_package.sh
  scripts/installer/nut
Labels: enhancement, CI

#2368 APC Modbus doc updates
  Jenkinsfile-dynamatrix
  docs/man/Makefile.am
  docs/man/apc_modbus.txt
  docs/nut.dict
  m4/nut_check_libmodbus.m4
  tools/nut-scanner/scan_snmp.c
  tools/nut-scanner/scan_xml_http.c
Labels: documentation, APC, USB, CI, modbus, impacts-release-2.8.1

#2366 Doc build recipe updates
  Makefile.am
  NEWS.adoc
  UPGRADING.adoc
  docs/Makefile.am
  docs/man/Makefile.am
  tools/gitlog2changelog.py.in
Labels: documentation, CI, portability

#2369 feat: Add support for Liebert PSI5
  NEWS.adoc
  drivers/belkin-hid.c
  drivers/usbhid-ups.c
  drivers/usbhid-ups.h
Labels: enhancement, USB, liebert

#1692 riello_usb.c: option for driver to calculate values of battery.runtime and battery.charge "locally"
  NEWS.adoc
  docs/man/riello_usb.txt
  docs/nut.dict
  drivers/riello_usb.c
Labels: USB, ready / gonna merge, Riello, Shutdowns and overrides and battery level triggers
