Repository networkupstools/nut, pull requests merged in 2024-02, with the labels that each got.

#2306 CI: Fix C/C++ standard customization
  Jenkinsfile-dynamatrix
  NEWS.adoc
  UPGRADING.adoc
  ci_build.sh
  clients/cgilib.c
  clients/upsmon.c
  clients/upssched.c
  common/common.c
  common/strptime.c
  configure.ac
  docs/developers.txt
  docs/nut.dict
  drivers/dstate.c
  drivers/eaton-pdu-marlin-mib.c
  drivers/main.c
  drivers/mge-hid.c
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx_ablerex.c
  drivers/pijuice.c
  drivers/riello.c
  drivers/riello_ser.c
  drivers/sms_ser.c
  drivers/snmp-ups.c
  drivers/snmp-ups.h
  drivers/tripplite_usb.c
  drivers/upsdrvctl.c
  drivers/upsdrvquery.c
  m4/nut_compiler_family.m4
  scripts/Windows/DriverInstaller/wdi-simple.c
  server/conf.c
  server/netssl.c
  server/pipedebug.c
  server/sockdebug.c
  server/sstate.c
  tests/generic_gpio_liblocal.c
  tests/generic_gpio_utest.c
Labels: bug, enhancement, Windows, CI, cross-builds, portability

#2305 CI: Fix NIT `isBusy_NUT_PORT()` method
  tests/NIT/nit.sh
Labels: enhancement, CI, portability

#2297 Fix: tripplite_usb: if upsid is not specified, make any unit ID match
  NEWS.adoc
  drivers/tripplite_usb.c
Labels: enhancement, Tripp Lite, USB, USB-duplicate-devices, impacts-release-2.8.1

#2285 snmp mib2nut wrapper macros
  drivers/apc-ats-mib.c
  drivers/apc-epdu-mib.c
  drivers/apc-mib.c
  drivers/apc-pdu-mib.c
  drivers/baytech-mib.c
  drivers/bestpower-mib.c
  drivers/compaq-mib.c
  drivers/cyberpower-mib.c
  drivers/delta_ups-mib.c
  drivers/eaton-ats16-nm2-mib.c
  drivers/eaton-ats16-nmc-mib.c
  drivers/eaton-ats30-mib.c
  drivers/eaton-pdu-genesis2-mib.c
  drivers/eaton-pdu-marlin-mib.c
  drivers/eaton-pdu-nlogic-mib.c
  drivers/eaton-pdu-pulizzi-mib.c
  drivers/eaton-pdu-revelation-mib.c
  drivers/eaton-ups-pwnm2-mib.c
  drivers/eaton-ups-pxg-mib.c
  drivers/emerson-avocent-pdu-mib.c
  drivers/hpe-pdu-mib.c
  drivers/hpe-pdu3-cis-mib.c
  drivers/huawei-mib.c
  drivers/ietf-mib.c
  drivers/mge-mib.c
  drivers/netvision-mib.c
  drivers/raritan-pdu-mib.c
  drivers/raritan-px2-mib.c
  drivers/snmp-ups-helpers.c
  drivers/snmp-ups.h
  drivers/xppc-mib.c
  scripts/subdriver/gen-snmp-subdriver.sh
Labels: SNMP, refactor/fightwarn, DMF

#2310 Introduce `configure --with-debuginfo` option for simpler dev-testing
  NEWS.adoc
  ci_build.sh
  configure.ac
  docs/nut.dict
  m4/nut_report_feature.m4
  tests/Makefile.am
Labels: Windows, CI, refactor/fightwarn, portability

#2313 [CI] `tests/NIT/nit.sh`: introduce `upsd_start_loop()`
  tests/NIT/nit.sh
Labels: enhancement, CI, portability

#2290 Enable build of libconf/nutconf features by default
  NEWS.adoc
  appveyor.yml
  ci_build.sh
  common/Makefile.am
  common/nutconf.cpp
  common/nutipc.cpp
  common/nutstream.cpp
  common/nutwriter.cpp
  configure.ac
  docs/man/Makefile.am
  docs/man/nutconf.txt
  docs/nut.dict
  include/Makefile.am
  include/nutconf.hpp
  include/nutipc.hpp
  include/nutstream.hpp
  include/nutwriter.hpp
  include/proto.h
  m4/ax_c_pragmas.m4
  tests/Makefile.am
  tests/cpputest.cpp
  tests/nutconf_parser_ut.cpp
  tests/nutconf_ut.cpp
  tests/nutipc_ut.cpp
  tests/nutstream_ut.cpp
  tools/Makefile.am
  tools/nut-scanner/nut-scan.h
  tools/nut-scanner/nut-scanner.c
  tools/nutconf/.gitignore
  tools/nutconf/Makefile.am
  tools/nutconf/nutconf-cli.cpp
Labels: feature, Windows, refactor/fightwarn, portability, nutconf

#2315 tests/nutipc_ut.cpp: use unique PID filenames for each test run
  include/nutstream.hpp
  tests/nutipc_ut.cpp
Labels: bug, nutconf

#2312 `drivers/cps-hid.c` et al: add support for Cyber Energy branded devices (by Cyber Power Systems)
  NEWS.adoc
  data/driver.list.in
  drivers/cps-hid.c
  drivers/ever-hid.c
  scripts/upower/95-upower-hid.hwdb
Labels: enhancement, CyberPower (CPS), USB

#2318 Fix `make docs` for runs made completely out-of-tree
  .gitignore
  Makefile.am
  NEWS.adoc
  README.adoc
  ci_build.sh
  clients/Makefile.am
  common/Makefile.am
  conf/Makefile.am
  data/Makefile.am
  data/html/Makefile.am
  docs/.gitignore
  docs/Makefile.am
  docs/images/ci/fosshost_org_Host_Dark_56px.png
  docs/images/ci/fosshost_org_Host_Light_309px.png
  docs/images/ci/fosshost_org_Host_Light_38px.png
  docs/images/ci/jenkins-nut.css
  docs/images/ci/jenkins-nut.txt
  docs/man/Makefile.am
  docs/nut.dict
  drivers/Makefile.am
  scripts/Makefile.am
  scripts/Solaris/Makefile.am
  scripts/Windows/Makefile.am
  scripts/devd/Makefile.am
  scripts/hotplug/Makefile.am
  scripts/installer/Makefile.am
  scripts/installer/common/README_ipp-os-shutdown.adoc
  scripts/python/Makefile.am
  scripts/python/module/Makefile.am
  scripts/python/module/README.adoc
  scripts/systemd/Makefile.am
  scripts/udev/Makefile.am
  scripts/upsdrvsvcctl/Makefile.am
  server/Makefile.am
  tests/Makefile.am
  tests/NIT/Makefile.am
  tools/gitlog2changelog.py.in
  tools/nut-scanner/Makefile.am
  tools/nutconf/Makefile.am
Labels: documentation, CI, refactor/fightwarn, portability

#2321 Fix docs generation of ChangeLog (in out-of-tree builds)
  Makefile.am
  docs/Makefile.am
Labels: documentation, CI, refactor/fightwarn, portability

#2322 `configure.ac`: revise detection of `LN_S_R` method applicable for the build (out-of-tree concerns)
  ci_build.sh
  configure.ac
Labels: CI, refactor/fightwarn, portability, DMF

#2326 Shell shebang
  indent.sh
  scripts/HP-UX/makedepot.sh
  scripts/Windows/build-mingw-nut.sh
  scripts/installer/make_package.sh
  scripts/subdriver/gen-snmp-subdriver.sh
  scripts/subdriver/gen-usbhid-subdriver.sh
Labels: CI, refactor/fightwarn, portability, impacts-release-2.8.1

#2327 Fix recipes for openbsd
  docs/config-prereqs.txt
  m4/nut_check_libltdl.m4
Labels: documentation, OpenBSD, nut-scanner, CI, portability, impacts-release-2.8.1

#2324 Correct access method used for flag battery_voltage_reports_one_pack
  NEWS.adoc
  drivers/nutdrv_qx.c
Labels: bug, Qx protocol driver, impacts-release-2.8.1
