Repository networkupstools/nut, pull requests merged in 2025-09, with the labels that each got.

#3071 docs/Makefile.am: Fix installation of the pdf files
  docs/Makefile.am
Labels: packaging, documentation, impacts-release-2.8.3, impacts-release-2.8.4

#3069 apc_modbus: Fix invalid memory access for USB vendor/product/serial
  drivers/apc_modbus.c
Labels: bug, APC, modbus, C-str, impacts-release-2.8.3, impacts-release-2.8.4

#3078 mge-hid: Improved support for Eaton 5S1500LCD (US version)
  NEWS.adoc
  drivers/mge-hid.c
Labels: enhancement, Eaton, USB, Incorrect or missing readings
