Repository networkupstools/nut, pull requests merged in 2025-05, with the labels that each got.

#2929 Fix `configure --with-drivers=dummy-ups`
  NEWS.adoc
  configure.ac
Labels: bug, CI, impacts-release-2.8.3

#2930 tests/Makefile.am: restructure and comment cppunittest_LDADD and cppnit_LDADD
  tests/Makefile.am
Labels: enhancement, C++, CI

#2932 Fix CI for "unmapped" data points, and update some docs
  NEWS.adoc
  ci_build.sh
  docs/Makefile.am
  docs/config-prereqs.txt
  docs/developers.txt
  docs/man/nutdrv_qx.txt
  docs/nut.dict
  docs/nutdrv_qx-subdrivers.txt
  drivers/nutdrv_qx_ablerex.c
  drivers/nutdrv_qx_ablerex.h
  drivers/powervar-hid.h
Labels: documentation, CI

#2944 Add APC BVKnnnnM2 to list of devices affected by spurious LB/RB messages
  NEWS.adoc
  UPGRADING.adoc
  data/driver.list.in
  docs/man/usbhid-ups.txt
  docs/nut.dict
  drivers/usbhid-ups.c
Labels: APC, USB, Incorrect or missing readings

#2946 Port NUT Monitor to Py3Qt6
  NEWS.adoc
  configure.ac
  docs/config-prereqs.txt
  docs/configure.txt
  docs/man/Makefile.am
  docs/man/NUT-Monitor.txt
  docs/new-clients.txt
  docs/nut.dict
  scripts/python/Makefile.am
  scripts/python/README.adoc
  scripts/python/app/.gitignore
  scripts/python/app/NUT-Monitor
  scripts/python/app/NUT-Monitor-py3qt6.in
  scripts/python/app/README.adoc
  scripts/python/app/locale/NUT-Monitor.pot
  scripts/python/app/locale/fr/fr.po
  scripts/python/app/locale/it/it.po
  scripts/python/app/locale/ru/ru.po
  scripts/python/app/nut-monitor-py3qt6.desktop
  scripts/python/app/ui/aboutdialog1.ui
  scripts/python/app/ui/gui-1.3.glade
  scripts/python/app/ui/gui-1.3.glade.h
Labels: python, portability

#2945 Add a way to `man nut` (new man section support, new page text)
  NEWS.adoc
  UPGRADING.adoc
  configure.ac
  docs/Makefile.am
  docs/configure.txt
  docs/download.txt
  docs/maintainer-guide.txt
  docs/man/Makefile.am
  docs/man/index.txt
  docs/man/nut.txt
  docs/nut.dict
Labels: feature, packaging, documentation, CI

#2940 drivers/nutdrv_hashx: Add new driver for PowerManager+ serial supported devices
  AUTHORS
  NEWS.adoc
  data/cmdvartab
  data/driver.list.in
  docs/Makefile.am
  docs/man/Makefile.am
  docs/man/nutdrv_hashx.txt
  docs/nut-names.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/nutdrv_hashx.c
  drivers/skel.c
Labels: feature, CyberPower (CPS), serial port, documentation-protocol, HashX protocol driver

#2938 Add support (experimental) for Ippon Innova RT 3/3
  NEWS.adoc
  docs/man/nutdrv_qx.txt
  docs/nutdrv_qx-subdrivers.txt
  drivers/Makefile.am
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx_blazer-common.c
  drivers/nutdrv_qx_blazer-common.h
  drivers/nutdrv_qx_innovart33.c
  drivers/nutdrv_qx_innovart33.h
Labels: enhancement, Ippon, Qx protocol driver

#2936 drivers/, dummy-ups: modernize status/alarm handling, ALARM instruction for dummy modes
  NEWS.adoc
  docs/man/dummy-ups.txt
  drivers/clone-outlet.c
  drivers/clone.c
  drivers/dummy-ups.c
  drivers/nhs_ser.c
  drivers/nutdrv_qx_ablerex.c
Labels: enhancement, refactor/fightwarn, NUT protocols, impacts-release-2.8.3

#2950 More recipe flexibility for man page sections and dir names (e.g. for Solaris/illumos)
  NEWS.adoc
  UPGRADING.adoc
  configure.ac
  docs/configure.txt
  docs/man/Makefile.am
  docs/man/apc_modbus.txt
  docs/man/blazer_ser.txt
  docs/man/blazer_usb.txt
  docs/man/generic_modbus.txt
  docs/man/networked_hostnames.txt
  docs/man/netxml-ups.txt
  docs/man/nut-ipmipsu.txt
  docs/man/nut.txt
  docs/man/powerman-pdu.txt
  docs/man/snmp-ups.txt
  docs/nut.dict
  scripts/python/app/locale/fr/LC_MESSAGES/NUT-Monitor.mo
  scripts/python/app/locale/it/LC_MESSAGES/NUT-Monitor.mo
  scripts/python/app/locale/ru/LC_MESSAGES/NUT-Monitor.mo
Labels: documentation, CI, Solaris/illumos

#2953 HCL automation: Driver list markup check
  Makefile.am
  data/.gitignore
  data/Makefile.am
  data/driver.list.in
  tools/Makefile.am
  tools/driver-list-format.sh
Labels: enhancement, HCL, packaging, CI

#2952 Increased the UPS equipment and corresponding descriptions from Ippon and Talegent manufacturers.
  data/driver.list.in
Labels: HCL, Ippon, serial port, impacts-release-2.7.4, impacts-release-2.8.3

#2947 Fix cmd for ecomode,bypass,experimental.ecomode.[start/stop].auto
  data/cmdvartab
  docs/nut-names.txt
  drivers/mge-hid.c
Labels: Eaton, USB, ECO/ESS/HE/ABM modes, impacts-release-2.8.3

#2955 Fix `usbhid-ups` instant commands that could work without non-trivial args before NUT v2.8.3
  NEWS.adoc
  docs/nut.dict
  drivers/usbhid-ups.c
  drivers/usbhid-ups.h
Labels: bug, USB, impacts-release-2.8.3

#2959 Help users address bad state files
  NEWS.adoc
  drivers/dstate.c
Labels: enhancement

#2966 Fix source markup for C89 compatibility, revise Jenkinsfile-dynamatrix
  Jenkinsfile-dynamatrix
  drivers/hwmon_ina219.c
  drivers/mge-hid.c
  m4/nut_check_libnss.m4
  tools/nut-scanner/nut-scanner.c
Labels: CI, portability

#2971 Various documentation updates
  docs/config-notes.txt
  docs/documentation.txt
  docs/man/Makefile.am
  docs/man/bestups.txt
  docs/man/index.txt
  docs/man/netxml-ups.txt
  docs/man/nut.txt
  docs/man/skel.txt
  docs/man/snmp-ups.txt
  docs/man/tripplite_usb.txt
  docs/man/ups.conf.txt
  docs/man/upsd.txt
  docs/man/upsmon.conf.txt
  docs/man/upsmon.txt
  docs/man/upssched.conf.txt
  docs/man/upsset.cgi.txt
  docs/nut.dict
  docs/security.txt
Labels: enhancement, documentation, CI, upsmon

#2972 drivers/main.c, drivers/dummy-ups.c: fix memory issues
  drivers/dummy-ups.c
  drivers/main.c
Labels: bug

#2969 upsdrvquery.{c,h}: add new one-shot functions for more versatile API use
  NEWS.adoc
  docs/nut.dict
  drivers/upsdrvquery.c
  drivers/upsdrvquery.h
Labels: enhancement, NUT protocols

#2963 common.c: VA copies with buffer upsizing, upsdrvquery.c: str handling fixes
  NEWS.adoc
  common/common.c
  configure.ac
  docs/nut.dict
  drivers/upsdrvquery.c
  include/common.h
Labels: bug, enhancement, refactor/fightwarn, impacts-release-2.8.2, C-str, impacts-release-2.8.3

#2973 Propose a `ci_build.sh` quicker matrix for `BUILD_TYPE=default-all-errors` scenarios
  Makefile.am
  NEWS.adoc
  ci_build.sh
  conf/upsmon.conf.sample.in
  configure.ac
  docs/man/index.txt
  docs/man/nut.txt
  docs/man/upsmon.conf.txt
  docs/man/usbhid-ups.txt
Labels: enhancement, documentation, CI, portability

#2962 failover.c - UPS Failover Driver
  NEWS.adoc
  docs/man/Makefile.am
  docs/man/failover.txt
  docs/man/nut-driver-enumerator.txt
  docs/nut.dict
  drivers/Makefile.am
  drivers/failover.c
  drivers/failover.h
  scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
  server/netget.c
  tests/nut-driver-enumerator-test.sh
Labels: feature, documentation, nut-driver-enumerator (NDE)
