Repository networkupstools/nut, pull requests merged in 2025-02, with the labels that each got.

#2796 Fix sms-brazil-protocol and sms_ser docs markup; quiesce driver service framework notifications when exiting due to bad CLI args
  NEWS.adoc
  docs/Makefile.am
  docs/man/sms_ser.txt
  docs/sms-brazil-protocol.txt
  drivers/main.c
Labels: enhancement, documentation, service/daemon start/stop

#2792 Socketify pynut
  COPYING
  NEWS.adoc
  configure.ac
  scripts/python/Makefile.am
  scripts/python/README.adoc
  scripts/python/module/Makefile.am
  scripts/python/module/PyNUT.py.in
  scripts/python/module/nut_telnetlib.py
  scripts/python/module/setup.py.in
  tests/NIT/nit.sh
Labels: enhancement, packaging, python, portability, impacts-release-2.8.2

#2799 More fixes to docs markup, recipes, scripting
  Makefile.am
  ci_build.sh
  configure.ac
  docs/Makefile.am
  docs/man/Makefile.am
  docs/man/nut_usb_addvars.txt
  docs/man/ups.conf.txt
Labels: enhancement, packaging, documentation, CI, portability

#2798 Q2 and Q6 protocols implementation
  NEWS.adoc
  docs/man/nutdrv_qx.txt
  docs/nut.dict
  docs/nutdrv_qx-subdrivers.txt
  drivers/Makefile.am
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx.h
  drivers/nutdrv_qx_blazer-common.c
  drivers/nutdrv_qx_blazer-common.h
  drivers/nutdrv_qx_innovart31.c
  drivers/nutdrv_qx_q2.c
  drivers/nutdrv_qx_q2.h
  drivers/nutdrv_qx_q6.c
  drivers/nutdrv_qx_q6.h
Labels: feature, Qx protocol driver

#2801 Fix handling of spaces in driver `status_set()` args
  NEWS.adoc
  appveyor.yml
  docs/new-drivers.txt
  drivers/bestfortress.c
  drivers/dstate.c
  drivers/liebert-gxe.c
  drivers/main.c
  tests/.gitignore
  tests/Makefile.am
  tests/driver_methods_utest.c
Labels: bug, enhancement, C-str

#2802 Fix battery runtime calculation for Q2 protocol
  drivers/nutdrv_qx.c
  drivers/nutdrv_qx.h
  drivers/nutdrv_qx_q2.c
Labels: feature, Qx protocol driver, Incorrect or missing readings

#2803 netvision-mib: sync netvision_output_info with SOCOMECUPS-MIB.txt
  NEWS.adoc
  UPGRADING.adoc
  docs/nut.dict
  drivers/netvision-mib.c
Labels: SNMP, Incorrect or missing readings, impacts-release-2.8.2

#2813 scripts/external_apis: add example external protocol script
  Makefile.am
  NEWS.adoc
  configure.ac
  docs/configure.txt
  docs/nut.dict
  scripts/Makefile.am
  scripts/external_apis/Makefile.am
  scripts/external_apis/README.adoc
  scripts/external_apis/enphase/.gitignore
  scripts/external_apis/enphase/README.adoc
  scripts/external_apis/enphase/enphase-monitor.in
  scripts/external_apis/enphase/enphase-monitor@.service.in
Labels: feature

#2817 Fix docs: add man page for `NUT-Monitor` UI client
  NEWS.adoc
  docs/man/Makefile.am
  docs/man/NUT-Monitor.txt
  scripts/python/app/NUT-Monitor
  scripts/systemd/nut-driver-enumerator-daemon-activator.path.in
  scripts/systemd/nut-driver-enumerator-daemon-activator.service.in
  scripts/systemd/nut-driver-enumerator-daemon.service.in
  scripts/systemd/nut-driver-enumerator.path.in
  scripts/systemd/nut-driver-enumerator.service.in
  scripts/systemd/nut-driver.target.in
  scripts/systemd/nut-driver@.service.in
  scripts/systemd/nut-logger.service.in
  scripts/systemd/nut-monitor.service.in
  scripts/systemd/nut-server.service.in
  scripts/systemd/nut-sleep.service
  scripts/systemd/nut-systemd.preset
  scripts/systemd/nut.target.in
  scripts/systemd/nutshutdown.in
Labels: documentation, python

#2823 Fix valgrind detection during configure script
  NEWS.adoc
  configure.ac
  scripts/Makefile.am
  scripts/valgrind/.gitignore
  scripts/valgrind/.valgrind.supp.in
Labels: Solaris/illumos, portability
